repos:
  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args:
        - "--profile=black"
        - "--filter-files"
  - repo: https://gitlab.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args:
        - "--max-line-length=100"
        - "--extend-ignore=E203"
        - "--per-file-ignores=__init__.py:F401"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.960"  # 2020.10.21
    hooks:
      - id: mypy
        additional_dependencies: [types-requests]
default_language_version:
  python: python3
