studies_folder = 'studies/'
experiment_folder = 'experimentation/'
models_folder = 'modeling/'
models_results_folder = 'results'
models_scripts_folder = 'scripts'
experiment_file_prefix = 'experiment_'
sequence_file_suffix = 'sequence'
data_file_suffix = 'data'

experiment_label = 'AER_Experiment'