{% set name = "autora" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 79b59b27b2ce85e5eca6b559cd09ba75eda6db3fdd497f0a140279794ff2c74e

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - autora

about:
  home: The package home page
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: "Autonomous Research Assistant (AutoRA) is a framework for implementing machine learning tools which autonomously and iteratively generate 1) new theories to describe real-world data, and 2) experiments to invalidate those theories and seed a new cycle of theory-making. The experiments will be run online via crowd-sourcing platforms (MTurk, Prolific)."
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
