{% set name = "autora" %}
{% set version = "0.0.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - poetry
  run:
    - graphviz
    - matplotlib >=3.2.1,<4.0.0
    - numpy >=1.23.1,<2.0.0
    - pandas >=1.4.2,<2.0.0
    - scikit-learn >=1.1.1,<2.0.0

test:
  requires:
    - pytest
  source_files:
    - tests
  imports:
    - autora
    - autora.cycle
    - autora.experimentalist
    - autora.variable

about:
  home: "https://musslick.github.io/AER_website/Research.html"
  license: UNKNOWN
  license_family: OTHER
  license_file: LICENSE.md
  summary: "Autonomous Research Assistant (AutoRA) is a framework for automating steps of the empirical research process. This framework implements tools for autonomously and iteratively generating 1) new theories to describe real-world data, and 2) experiments to invalidate those theories and seed a new cycle of theory-making. The experiments will be run online via crowd-sourcing platforms (MTurk, Prolific)."
  doc_url: https://autoresearch.github.io/autora/
  dev_url: https://github.com/AutoResearch/autora

extra:
  recipe-maintainers:
    - musslick
    - hollandjg
    - benwandrew
