{% set name = "autora" %}
{% set version = "1.0.0a1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../../

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - poetry
    - graphviz
    - python-graphviz >=0.14.1,<0.15.0
    - imageio >=2.9.0,<2.10.0
    - matplotlib >=3.2.1,<4.0.0
    - numpy >=1.18,<2.0
    - pandas >=1.4.2,<1.5.0
    - scikit-learn >=1.1.1,<2.0.0
    - scipy >=1.7.1,<2.0.0
    - seaborn >=0.11.1,<0.12.0
    - pytorch >=1.11.0,<2.0.0
    - tqdm >=4.64.0,<5.0.0
  run:
    - python
    - graphviz
    - python-graphviz >=0.14.1,<0.15.0
    - imageio >=2.9.0,<2.10.0
    - matplotlib >=3.2.1,<4.0.0
    - numpy >=1.18,<2.0
    - pandas >=1.4.2,<1.5.0
    - scikit-learn >=1.1.1,<2.0.0
    - scipy >=1.7.1,<2.0.0
    - seaborn >=0.11.1,<0.12.0
    - pytorch >=1.11.0,<2.0.0
    - tqdm >=4.64.0,<5.0.0

test:
  imports:
    - autora
    - autora.skl
    - autora.theorist
    - autora.theorist.darts
    - autora.variable

about:
  home: The package home page
  license: UNKNOWN
  license_family: OTHER
  license_file:
  summary: "Autonomous Research Assistant (AutoRA) is a framework for implementing machine learning tools which autonomously and iteratively generate 1) new theories to describe real-world data, and 2) experiments to invalidate those theories and seed a new cycle of theory-making. The experiments will be run online via crowd-sourcing platforms (MTurk, Prolific)."
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - hollandjg
