name: Deploy to Anaconda.org

on:
  release:
    types: [ published ]

jobs:
  build-conda:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Bump version number
      uses: nguyenvanuyn96/str-find-and-replace-action@0.0.5
      with:
        include: conda/recipe/meta.yaml
        find: '{% set version = "0.0.0" %}'
        replace: '{% set version = "${{ github.event.release.tag_name }}" %}'

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        
    - name: Install dependencies
      run: conda install conda-build
    
    - name: Build
      run: conda build ./conda/recipe -c pytorch --output-folder conda/dist/
        
