name: Deploy to PyPI

on:
  release:
    types: [ published ]

jobs:
  
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      
      - run: pipx install poetry
    
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install
  
      - run: poetry version ${{ github.event.release.tag_name }}
      
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: bump version to ${{ github.event.release.tag_name }}"

      - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      
      - run: poetry config pypi-token.testpypi ${{ secrets.PYPI_TOKEN }}      
      
      - run: poetry publish --repository=testpypi --build 
