name: Deploy to PyPI

on:
  release:
    types: [ published ]

jobs:
  
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - run: pipx install poetry
      
      - run: poetry self add "poetry-dynamic-versioning[plugin]"
    
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install
  
      - run: poetry build

      - run: poetry config repositories.testpypi https://test.pypi.org/legacy/
      
      - run: poetry config pypi-token.testpypi ${{ secrets.PYPI_TOKEN }}      
      
      - run: poetry publish --repository=testpypi
