name: Deploy to Anaconda.org

on:
  release:
    types: [ published ]

jobs:
  build-conda:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Bump version number
      run: |
        REF_NAME_WITHOUT_V=${GITHUB_REF_NAME#v}
        sed -i.bak "s/{% set version = \"0.0.0\" %}/{% set version = \"${REF_NAME_WITHOUT_V}\" %}/" conda/autora/meta.yaml

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
        
    - name: Install dependencies
      run: | 
        conda install conda-build
        conda install conda-verify
        conda install anaconda-client
    
    - name: Build
      run: |
        cd ./conda
        conda config --set anaconda_upload yes
        conda build autora -c pytorch --token "${{ secrets.ANACONDA_TOKEN }}"
        
