name: Publish Documentation to GitHub Pages

on:
  workflow_dispatch:  # this allows us to run it manually
  release:
    types: [released]  # only deploy when we make a new `latest` release

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -U ".[docs]"
      - run: mkdocs gh-deploy --force
