# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test pre-commit-hooks

on:
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: pipx install poetry
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
        cache: "poetry"
    - run: poetry install --only pre-commit
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ env.pythonLocation }}|${{ runner.os }}|${{ hashFiles('.pre-commit-config.yaml') }}
    - run: poetry run pre-commit run --all-files --show-diff-on-failure --color=always
