# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

# Shared configuration matching the rest of the AutoRA documentation.
theme:
  name: material

plugins:
  multirepo: {}
  mkdocs-jupyter:  # required to convert Jupyter notebooks
    include_source: true
    execute: false
    ignore_h1_titles: true

markdown_extensions:
  admonition: {}
  pymdownx.details: {}
  pymdownx.superfences: {}
  pymdownx.arithmatex: # required for equation display
    generic: true

extra_javascript: [ 
  # requirements for pymdownx.arithmetex:
  "javascripts/mathjax.js",                                 
  "https://polyfill.io/v3/polyfill.min.js?features=es6", 
  "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"
]
